apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-a
  namespace: dev
spec:
  project: helm-guestbook
  source:
    repoURL: https://github.com/dustinvanbuskirk/helm-guestbook-a.git
    path: helm-guestbook-a
    targetRevision: main
    # helm specific config
    helm:
      # Release name override (defaults to application name)
      releaseName: helm-guestbook-a
      # Helm values files for overriding values in the helm chart
      # The path is relative to the spec.source.path directory defined above
      valueFiles:
      - ../environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev